ingress:
  enabled: true

prometheus:
  rbac:
    create: false
  serviceAccounts:
    alertmanager:
      name: default
      create: false
    nodeExporter:
      name: default
      create: false
    kubeStateMetrics:
      name: default
      create: false
    pushgateway:
      name: default
      create: false
    server:
      name: default
      create: false

zenko-queue:
  rbac:
    enabled: false
  configurationOverrides:
    "offsets.topic.replication.factor": 1 # - replication factor for the offsets topic
    "num.partitions": 1                   # - default number of log partitions per topic
    "auto.create.topics.enable": true     # - enable auto creation of topic on the server
    "min.insync.replicas": 1              # - min number of replicas that must acknowledge a write

redis-ha:
  rbac:
    create: false
  serviceAccount:
    create: false
    name: default

cloudserver:
  resources:
    limits:
      cpu: 1
      memory: 8Gi
    requests:
      cpu: 1
      memory: 8Gi
  image:
    pullPolicy: Always
  orbit:
    endpoint: "http://ciutil-orbit-simulator:4222"
    managerMode: "poll"
  replicaCount: 0
  env:
    MPU_TESTING: 'yes'

backbeat:
  lifecycle:
    conductor:
      cronRule: "0 */1 * * * *"

grafana:
  rbac:
    create: false
    pspEnabled: false
  serviceAccount:
    create: false
  adminUser: admin
  adminPassword: strongpassword
